version: '3.4'

services:
  sql:
    image: mcr.microsoft.com/mssql/server:2022-latest
    environment:
      - ACCEPT_EULA=Y
      - MSSQL_SA_PASSWORD=P@ssw0rd
    ports:
      - 1433:1433
    volumes:
      - sqlvolume:/var/opt/mssql
  api:
    image: ${DOCKER_REGISTRY-}whats-for-dinner-api
    build:
      context: .
      dockerfile: src/WhatsForDinner.Api/Dockerfile
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_HTTPS_PORTS=8081
      - SqlServer__ConnectionString=Server=sql,1433;Database=WhatsForDinner;User=sa;Password=P@ssw0rd;TrustServerCertificate=true;
    ports:
      - 5000:8081
    volumes:
      - ${APPDATA}/ASP.NET/Https:/home/app/.aspnet/https:ro
    depends_on:
      - sql
  spa:
    image: ${DOCKER_REGISTRY-}whats-for-dinner-spa
    build:
      context: src/whats-for-dinner-spa
      dockerfile: Dockerfile
    ports:
      - 4200:4200
    volumes:
      - ./src/whats-for-dinner-spa:/app
      - spa_node_modules:/app/node_modules
  web:
    image: ${DOCKER_REGISTRY-}whats-for-dinner-web
    build:
      context: .
      dockerfile: src/WhatsForDinner.Web/Dockerfile
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_HTTPS_PORTS=8081
      - Yarp__ApiUrl=https://api:8081
      - Yarp__AngularDevServerUrl=http://spa:4200
    ports:
      - 5001:8081
    volumes:
      - ${APPDATA}/ASP.NET/Https:/home/app/.aspnet/https:ro
    depends_on:
      - api
      - spa
volumes:
  sqlvolume:
  spa_node_modules:  