version: '3.4'

services:
  sqlserver:
    image: mcr.microsoft.com/mssql/server:2022-latest
    environment:
      - ACCEPT_EULA=Y
      - MSSQL_SA_PASSWORD=P@ssw0rd
    ports:
      - 1433:1433
    volumes:
      - sqlservervolume:/var/opt/mssql
  web:
    image: ${DOCKER_REGISTRY-}whats-for-dinner-web
    build:
      context: .
      dockerfile: src/WhatsForDinner.Web/Dockerfile
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_HTTPS_PORTS=8081
      - SqlServer__ConnectionString=Server=sqlserver,1433;Database=WhatsForDinner;User=sa;Password=P@ssw0rd;TrustServerCertificate=true;
    ports:
      - 5000:8081
    volumes:
      - ${APPDATA}/ASP.NET/Https:/home/app/.aspnet/https:ro
    depends_on:
      - sqlserver
  spa:
    image: ${DOCKER_REGISTRY-}whats-for-dinner-spa
    build:
      context: src/whats-for-dinner-spa
      dockerfile: Dockerfile
    ports:
      - 5001:4200
    depends_on:
      - web
volumes:
  sqlservervolume: